// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 04.11.2025, 22:17:35
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["D:/JS_project/luis-konsultant/components/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/JS_project/luis-konsultant/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/JS_project/luis-konsultant/components/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/JS_project/luis-konsultant/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/JS_project/luis-konsultant/plugins/**/*.{js,ts,mjs}","D:/JS_project/luis-konsultant/composables/**/*.{js,ts,mjs}","D:/JS_project/luis-konsultant/utils/**/*.{js,ts,mjs}","D:/JS_project/luis-konsultant/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/JS_project/luis-konsultant/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","D:/JS_project/luis-konsultant/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","D:/JS_project/luis-konsultant/app.config.{js,ts,mjs}","D:/JS_project/luis-konsultant/app/spa-loading-template.html"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;